typography_spectrum: 0.57447
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75416
analytics:
  google: null
  facebook: null
  twitter: null
name: Art Of Freedom
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Volunteer
    id: dbfb3256-b666-448d-8abd-ff06ec0e3d2f
    type: content
favicon: null
title: Art Of Freedom
purpose: []
