name: Art Of Freedom
favicon: null
layout_spectrum: 0.75416
typography_spectrum: 0.57447
title: EMPOWERING VICTIMS OF HUMAN TRAFFICKING.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
